import { MigrationInterface, QueryRunner } from "typeorm";

export class InitSchema1767415531020 implements MigrationInterface {
    name = 'InitSchema1767415531020'

    public async up(queryRunner: QueryRunner): Promise<void> {
        await queryRunner.query(`CREATE TABLE "driver_locations" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "driverId" uuid NOT NULL, "location" geometry(Point,4326) NOT NULL, "heading" double precision, "speed" double precision, "timestamp" TIMESTAMP NOT NULL DEFAULT now(), CONSTRAINT "PK_31aae5c417762bf01ec26a53f02" PRIMARY KEY ("id")); COMMENT ON COLUMN "driver_locations"."location" IS 'Driver location as PostGIS Point (longitude, latitude in SRID 4326)'; COMMENT ON COLUMN "driver_locations"."heading" IS 'Heading in degrees (0-360)'; COMMENT ON COLUMN "driver_locations"."speed" IS 'Speed in km/h'`);
        await queryRunner.query(`CREATE INDEX "IDX_c1c468ee6db1b2b400e418cf8c" ON "driver_locations" USING GiST ("location") `);
        await queryRunner.query(`CREATE INDEX "IDX_62df81b116734099734d24a992" ON "driver_locations" ("driverId") `);
        await queryRunner.query(`CREATE INDEX "IDX_a83a6e195db1b0b5aca2f551ae" ON "driver_locations" ("driverId", "timestamp") `);
        await queryRunner.query(`CREATE TABLE "orders" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "pickupLocation" geometry(Point,4326) NOT NULL, "pickupAddress" character varying(255) NOT NULL, "dropoffLocation" geometry(Point,4326) NOT NULL, "dropoffAddress" character varying(255) NOT NULL, "requestedDeliveryDate" date NOT NULL, "preferredTimeSlot" character varying(50), "status" "public"."orders_status_enum" NOT NULL DEFAULT 'pending', "priority" integer NOT NULL DEFAULT '5', "value" double precision NOT NULL DEFAULT '0', "rejectedDriverIds" text array NOT NULL DEFAULT '{}', "rejectionCount" integer NOT NULL DEFAULT '0', "priorityMultiplier" double precision NOT NULL DEFAULT '1', "createdAt" TIMESTAMP NOT NULL DEFAULT now(), "updatedAt" TIMESTAMP NOT NULL DEFAULT now(), CONSTRAINT "PK_710e2d4957aa5878dfe94e4ac2f" PRIMARY KEY ("id")); COMMENT ON COLUMN "orders"."pickupLocation" IS 'Pickup location as PostGIS Point (longitude, latitude in SRID 4326)'; COMMENT ON COLUMN "orders"."dropoffLocation" IS 'Dropoff location as PostGIS Point (longitude, latitude in SRID 4326)'; COMMENT ON COLUMN "orders"."requestedDeliveryDate" IS 'Requested delivery date - system will generate optimal time window after route optimization'; COMMENT ON COLUMN "orders"."preferredTimeSlot" IS 'Optional time preference: morning | afternoon | evening | null (flexible)'; COMMENT ON COLUMN "orders"."priority" IS 'Priority 1-10, higher = more urgent'; COMMENT ON COLUMN "orders"."value" IS 'Order value in dollars'; COMMENT ON COLUMN "orders"."rejectedDriverIds" IS 'Driver IDs that have rejected this order'; COMMENT ON COLUMN "orders"."rejectionCount" IS 'Total number of rejections for this order'; COMMENT ON COLUMN "orders"."priorityMultiplier" IS 'Priority multiplier - increases with rejections'`);
        await queryRunner.query(`CREATE INDEX "IDX_5f014649aa5b64265b7fd3c3c4" ON "orders" USING GiST ("dropoffLocation") `);
        await queryRunner.query(`CREATE INDEX "IDX_5fe4a45aea3bb1064ef605c9ca" ON "orders" USING GiST ("pickupLocation") `);
        await queryRunner.query(`CREATE INDEX "IDX_5cf46517f97cf0f46c60796379" ON "orders" ("requestedDeliveryDate") `);
        await queryRunner.query(`CREATE INDEX "IDX_775c9f06fc27ae3ff8fb26f2c4" ON "orders" ("status") `);
        await queryRunner.query(`CREATE TYPE "public"."order_assignments_status_enum" AS ENUM('offered', 'accepted', 'rejected', 'expired', 'completed', 'cancelled')`);
        await queryRunner.query(`CREATE TABLE "order_assignments" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "orderId" uuid NOT NULL, "driverId" uuid NOT NULL, "sequence" integer NOT NULL, "status" "public"."order_assignments_status_enum" NOT NULL DEFAULT 'offered', "offerExpiresAt" TIMESTAMP, "rejectionReason" text, "respondedAt" TIMESTAMP, "offerRound" integer NOT NULL DEFAULT '1', "estimatedPickup" TIMESTAMP NOT NULL, "estimatedDelivery" TIMESTAMP NOT NULL, "actualPickup" TIMESTAMP, "actualDelivery" TIMESTAMP, "assignedAt" TIMESTAMP NOT NULL DEFAULT now(), "updatedAt" TIMESTAMP NOT NULL DEFAULT now(), "timeWindow" jsonb, CONSTRAINT "UQ_be2c5ad5e40bd737781a9b6c2c4" UNIQUE ("orderId"), CONSTRAINT "REL_be2c5ad5e40bd737781a9b6c2c" UNIQUE ("orderId"), CONSTRAINT "PK_519d4a549818b74ed40f72dd893" PRIMARY KEY ("id")); COMMENT ON COLUMN "order_assignments"."sequence" IS 'Position in driver route sequence (1-based)'; COMMENT ON COLUMN "order_assignments"."status" IS 'Assignment status in the offer-accept-reject lifecycle'; COMMENT ON COLUMN "order_assignments"."offerExpiresAt" IS 'When this offer expires (auto-reject after timeout)'; COMMENT ON COLUMN "order_assignments"."rejectionReason" IS 'Reason provided by driver for rejection'; COMMENT ON COLUMN "order_assignments"."respondedAt" IS 'When driver accepted or rejected this assignment'; COMMENT ON COLUMN "order_assignments"."offerRound" IS 'Which draft cycle created this assignment'; COMMENT ON COLUMN "order_assignments"."estimatedPickup" IS 'Estimated pickup time (before time window optimization)'; COMMENT ON COLUMN "order_assignments"."estimatedDelivery" IS 'Estimated delivery time (before time window optimization)'; COMMENT ON COLUMN "order_assignments"."timeWindow" IS 'Time window optimization result from algorithm'`);
        await queryRunner.query(`CREATE INDEX "IDX_be2c5ad5e40bd737781a9b6c2c" ON "order_assignments" ("orderId") `);
        await queryRunner.query(`CREATE INDEX "IDX_d77e417aee937376759f922580" ON "order_assignments" ("driverId") `);
        await queryRunner.query(`CREATE TABLE "drivers" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "name" character varying(255) NOT NULL, "phone" character varying(20) NOT NULL, "vehicleType" character varying(50) NOT NULL, "maxOrders" integer NOT NULL DEFAULT '3', "status" "public"."drivers_status_enum" NOT NULL DEFAULT 'offline', "createdAt" TIMESTAMP NOT NULL DEFAULT now(), "updatedAt" TIMESTAMP NOT NULL DEFAULT now(), CONSTRAINT "UQ_b97a5a68c766d2d1ec25e6a85b2" UNIQUE ("phone"), CONSTRAINT "PK_92ab3fb69e566d3eb0cae896047" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE TABLE "time_windows" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "orderId" uuid NOT NULL, "driverId" uuid NOT NULL, "lowerBound" TIMESTAMP NOT NULL, "upperBound" TIMESTAMP NOT NULL, "windowWidthSeconds" integer NOT NULL, "expectedArrival" TIMESTAMP NOT NULL, "confidenceLevel" double precision NOT NULL, "violationProbability" double precision NOT NULL, "penaltyWidth" double precision NOT NULL, "penaltyEarly" double precision NOT NULL, "penaltyLate" double precision NOT NULL, "calculationMethod" character varying(50) NOT NULL, "sampleCount" integer, "travelTimeStdDev" double precision, "coefficientOfVariation" double precision, "actualArrival" TIMESTAMP, "wasWithinWindow" boolean, "deviationSeconds" integer, "createdAt" TIMESTAMP NOT NULL DEFAULT now(), "updatedAt" TIMESTAMP NOT NULL DEFAULT now(), CONSTRAINT "UQ_9c520f9d67b0d5fe2582df4bed1" UNIQUE ("orderId"), CONSTRAINT "PK_afd49e0b76e7f51b7ba8530741e" PRIMARY KEY ("id")); COMMENT ON COLUMN "time_windows"."lowerBound" IS 'Lower bound ℓ: earliest service time'; COMMENT ON COLUMN "time_windows"."upperBound" IS 'Upper bound u: latest service time'; COMMENT ON COLUMN "time_windows"."windowWidthSeconds" IS 'Window width in seconds: u - ℓ'; COMMENT ON COLUMN "time_windows"."expectedArrival" IS 'Expected arrival time E[T^k]'; COMMENT ON COLUMN "time_windows"."confidenceLevel" IS 'Service level guarantee (0-1): P(arrival ∈ [ℓ,u]). e.g., 0.95 = 95% on-time probability'; COMMENT ON COLUMN "time_windows"."violationProbability" IS 'Violation probability: 1 - confidenceLevel'; COMMENT ON COLUMN "time_windows"."penaltyWidth" IS 'Penalty a_w: cost per second of window width'; COMMENT ON COLUMN "time_windows"."penaltyEarly" IS 'Penalty a_ℓ: cost of early arrival'; COMMENT ON COLUMN "time_windows"."penaltyLate" IS 'Penalty a_u: cost of late arrival'; COMMENT ON COLUMN "time_windows"."calculationMethod" IS 'Method: stochastic_saa | distributionally_robust | simple_heuristic'; COMMENT ON COLUMN "time_windows"."sampleCount" IS 'Number of historical observations used (SAA)'; COMMENT ON COLUMN "time_windows"."travelTimeStdDev" IS 'Travel time standard deviation (seconds)'; COMMENT ON COLUMN "time_windows"."coefficientOfVariation" IS 'Coefficient of variation: σ/μ'; COMMENT ON COLUMN "time_windows"."wasWithinWindow" IS 'Whether actual ∈ [ℓ, u]'; COMMENT ON COLUMN "time_windows"."deviationSeconds" IS 'Deviation in seconds: negative=early, positive=late'`);
        await queryRunner.query(`CREATE INDEX "IDX_9513d5e67d8e59f34d287f4631" ON "time_windows" ("calculationMethod") `);
        await queryRunner.query(`CREATE INDEX "IDX_13a9408f6f3b9b83ecc6637ee6" ON "time_windows" ("lowerBound", "upperBound") `);
        await queryRunner.query(`CREATE INDEX "IDX_84fc02f476b986defb647630de" ON "time_windows" ("driverId") `);
        await queryRunner.query(`CREATE INDEX "IDX_9c520f9d67b0d5fe2582df4bed" ON "time_windows" ("orderId") `);
        await queryRunner.query(`CREATE TABLE "route_segment_observations" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "routeSegment" geometry(LineString,4326) NOT NULL, "estimatedSeconds" integer NOT NULL, "actualSeconds" integer NOT NULL, "deviationSeconds" integer NOT NULL, "distanceMeters" double precision NOT NULL, "driverId" uuid, "timeOfDay" character varying(20), "dayOfWeek" character varying(20), "weatherCondition" character varying(50), "timestamp" TIMESTAMP NOT NULL DEFAULT now(), CONSTRAINT "PK_953644963c282af0335e8efe4d3" PRIMARY KEY ("id")); COMMENT ON COLUMN "route_segment_observations"."routeSegment" IS 'Route segment as PostGIS LineString (start → end in SRID 4326)'; COMMENT ON COLUMN "route_segment_observations"."estimatedSeconds" IS 'Estimated travel time in seconds (from routing algorithm)'; COMMENT ON COLUMN "route_segment_observations"."actualSeconds" IS 'Actual observed travel time in seconds'; COMMENT ON COLUMN "route_segment_observations"."deviationSeconds" IS 'Deviation: actual - estimated (seconds, can be negative)'; COMMENT ON COLUMN "route_segment_observations"."distanceMeters" IS 'Distance calculated by PostGIS ST_Length using geography type (meters)'; COMMENT ON COLUMN "route_segment_observations"."timeOfDay" IS 'Time bucket: morning (6-12), afternoon (12-18), evening (18-22), night (22-6)'; COMMENT ON COLUMN "route_segment_observations"."dayOfWeek" IS 'Day: monday, tuesday, wednesday, thursday, friday, saturday, sunday'; COMMENT ON COLUMN "route_segment_observations"."weatherCondition" IS 'Weather condition during travel (if available)'`);
        await queryRunner.query(`CREATE INDEX "IDX_41db42720b56dc995cd3ec4e76" ON "route_segment_observations" USING GiST ("routeSegment") `);
        await queryRunner.query(`CREATE INDEX "IDX_f3205d0df4431d572cb49727c9" ON "route_segment_observations" ("timeOfDay", "dayOfWeek") `);
        await queryRunner.query(`CREATE INDEX "IDX_f7e295692ce643d0da805e05e8" ON "route_segment_observations" ("timestamp") `);
        await queryRunner.query(`CREATE INDEX "IDX_ce24c34d30d3389295db1c9fb1" ON "route_segment_observations" ("driverId") `);
        await queryRunner.query(`ALTER TABLE "driver_locations" ADD CONSTRAINT "FK_62df81b116734099734d24a992a" FOREIGN KEY ("driverId") REFERENCES "drivers"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "order_assignments" ADD CONSTRAINT "FK_be2c5ad5e40bd737781a9b6c2c4" FOREIGN KEY ("orderId") REFERENCES "orders"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "order_assignments" ADD CONSTRAINT "FK_d77e417aee937376759f9225803" FOREIGN KEY ("driverId") REFERENCES "drivers"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
    }

    public async down(queryRunner: QueryRunner): Promise<void> {
        await queryRunner.query(`ALTER TABLE "order_assignments" DROP CONSTRAINT "FK_d77e417aee937376759f9225803"`);
        await queryRunner.query(`ALTER TABLE "order_assignments" DROP CONSTRAINT "FK_be2c5ad5e40bd737781a9b6c2c4"`);
        await queryRunner.query(`ALTER TABLE "driver_locations" DROP CONSTRAINT "FK_62df81b116734099734d24a992a"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_ce24c34d30d3389295db1c9fb1"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_f7e295692ce643d0da805e05e8"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_f3205d0df4431d572cb49727c9"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_41db42720b56dc995cd3ec4e76"`);
        await queryRunner.query(`DROP TABLE "route_segment_observations"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_9c520f9d67b0d5fe2582df4bed"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_84fc02f476b986defb647630de"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_13a9408f6f3b9b83ecc6637ee6"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_9513d5e67d8e59f34d287f4631"`);
        await queryRunner.query(`DROP TABLE "time_windows"`);
        await queryRunner.query(`DROP TABLE "drivers"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_d77e417aee937376759f922580"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_be2c5ad5e40bd737781a9b6c2c"`);
        await queryRunner.query(`DROP TABLE "order_assignments"`);
        await queryRunner.query(`DROP TYPE "public"."order_assignments_status_enum"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_775c9f06fc27ae3ff8fb26f2c4"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_5cf46517f97cf0f46c60796379"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_5fe4a45aea3bb1064ef605c9ca"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_5f014649aa5b64265b7fd3c3c4"`);
        await queryRunner.query(`DROP TABLE "orders"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_a83a6e195db1b0b5aca2f551ae"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_62df81b116734099734d24a992"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_c1c468ee6db1b2b400e418cf8c"`);
        await queryRunner.query(`DROP TABLE "driver_locations"`);
    }

}
