import { MigrationInterface, QueryRunner } from "typeorm";

export class InitSchema1768143064090 implements MigrationInterface {
    name = 'InitSchema1768143064090'

    public async up(queryRunner: QueryRunner): Promise<void> {
        await queryRunner.query(`CREATE TABLE "driver_locations" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "driver_id" uuid NOT NULL, "location" geometry(Point,4326) NOT NULL, "heading" double precision, "speed" double precision, "timestamp" TIMESTAMP NOT NULL DEFAULT now(), CONSTRAINT "PK_31aae5c417762bf01ec26a53f02" PRIMARY KEY ("id")); COMMENT ON COLUMN "driver_locations"."location" IS 'Driver location as PostGIS Point (longitude, latitude in SRID 4326)'; COMMENT ON COLUMN "driver_locations"."heading" IS 'Heading in degrees (0-360)'; COMMENT ON COLUMN "driver_locations"."speed" IS 'Speed in km/h'`);
        await queryRunner.query(`CREATE TABLE "customers" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "name" character varying(255) NOT NULL, "email" character varying(255) NOT NULL, "phone" character varying(20) NOT NULL, "defaultAddress" character varying(500), "defaultLocation" geometry(Point,4326), "createdAt" TIMESTAMP NOT NULL DEFAULT now(), "updatedAt" TIMESTAMP NOT NULL DEFAULT now(), CONSTRAINT "UQ_8536b8b85c06969f84f0c098b03" UNIQUE ("email"), CONSTRAINT "UQ_88acd889fbe17d0e16cc4bc9174" UNIQUE ("phone"), CONSTRAINT "PK_133ec679a801fab5e070f73d3ea" PRIMARY KEY ("id")); COMMENT ON COLUMN "customers"."defaultLocation" IS 'Default location as PostGIS Point (longitude, latitude)'`);
        await queryRunner.query(`CREATE TABLE "orders" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "customerId" uuid, "pickupLocation" geometry(Point,4326) NOT NULL, "pickupAddress" character varying(255) NOT NULL, "dropoffLocation" geometry(Point,4326) NOT NULL, "dropoffAddress" character varying(255) NOT NULL, "requestedDeliveryDate" date NOT NULL, "preferredTimeSlot" character varying(50), "status" "public"."orders_status_enum" NOT NULL DEFAULT 'pending', "priority" integer NOT NULL DEFAULT '5', "value" double precision NOT NULL DEFAULT '0', "estimatedDistance" double precision, "estimatedDuration" double precision, "rejectedDriverIds" text array NOT NULL DEFAULT '{}', "rejectionCount" integer NOT NULL DEFAULT '0', "priorityMultiplier" double precision NOT NULL DEFAULT '1', "createdAt" TIMESTAMP NOT NULL DEFAULT now(), "updatedAt" TIMESTAMP NOT NULL DEFAULT now(), CONSTRAINT "PK_710e2d4957aa5878dfe94e4ac2f" PRIMARY KEY ("id")); COMMENT ON COLUMN "orders"."pickupLocation" IS 'Pickup location as PostGIS Point (longitude, latitude in SRID 4326)'; COMMENT ON COLUMN "orders"."dropoffLocation" IS 'Dropoff location as PostGIS Point (longitude, latitude in SRID 4326)'; COMMENT ON COLUMN "orders"."requestedDeliveryDate" IS 'Requested delivery date - system will generate optimal time window after route optimization'; COMMENT ON COLUMN "orders"."preferredTimeSlot" IS 'Optional time preference: morning | afternoon | evening | null (flexible)'; COMMENT ON COLUMN "orders"."priority" IS 'Priority 1-10, higher = more urgent'; COMMENT ON COLUMN "orders"."value" IS 'Order value in dollars'; COMMENT ON COLUMN "orders"."estimatedDistance" IS 'Estimated distance from pickup to dropoff in meters'; COMMENT ON COLUMN "orders"."estimatedDuration" IS 'Estimated duration from pickup to dropoff in seconds'; COMMENT ON COLUMN "orders"."rejectedDriverIds" IS 'Driver IDs that have rejected this order'; COMMENT ON COLUMN "orders"."rejectionCount" IS 'Total number of rejections for this order'; COMMENT ON COLUMN "orders"."priorityMultiplier" IS 'Priority multiplier - increases with rejections'`);
        await queryRunner.query(`CREATE TABLE "order_assignments" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "order_id" uuid NOT NULL, "driver_id" uuid NOT NULL, "sequence" integer NOT NULL, "status" "public"."order_assignments_status_enum" NOT NULL DEFAULT 'offered', "offerExpiresAt" TIMESTAMP, "rejectionReason" text, "respondedAt" TIMESTAMP, "offerRound" integer NOT NULL DEFAULT '1', "estimatedPickup" TIMESTAMP NOT NULL, "estimatedDelivery" TIMESTAMP NOT NULL, "actualPickup" TIMESTAMP, "actualDelivery" TIMESTAMP, "assignedAt" TIMESTAMP NOT NULL DEFAULT now(), "updatedAt" TIMESTAMP NOT NULL DEFAULT now(), "timeWindow" jsonb, CONSTRAINT "REL_2879b5a864ad805fe7332f6834" UNIQUE ("order_id"), CONSTRAINT "PK_519d4a549818b74ed40f72dd893" PRIMARY KEY ("id")); COMMENT ON COLUMN "order_assignments"."sequence" IS 'Position in driver route sequence (1-based)'; COMMENT ON COLUMN "order_assignments"."status" IS 'Assignment status in the offer-accept-reject lifecycle'; COMMENT ON COLUMN "order_assignments"."offerExpiresAt" IS 'When this offer expires (auto-reject after timeout)'; COMMENT ON COLUMN "order_assignments"."rejectionReason" IS 'Reason provided by driver for rejection'; COMMENT ON COLUMN "order_assignments"."respondedAt" IS 'When driver accepted or rejected this assignment'; COMMENT ON COLUMN "order_assignments"."offerRound" IS 'Which draft cycle created this assignment'; COMMENT ON COLUMN "order_assignments"."estimatedPickup" IS 'Estimated pickup time (before time window optimization)'; COMMENT ON COLUMN "order_assignments"."estimatedDelivery" IS 'Estimated delivery time (before time window optimization)'; COMMENT ON COLUMN "order_assignments"."timeWindow" IS 'Time window optimization result from algorithm'`);
        await queryRunner.query(`CREATE TABLE "drivers" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "name" character varying(255) NOT NULL, "phone" character varying(20) NOT NULL, "vehicleType" character varying(50) NOT NULL, "maxOrders" integer NOT NULL DEFAULT '3', "status" "public"."drivers_status_enum" NOT NULL DEFAULT 'offline', "createdAt" TIMESTAMP NOT NULL DEFAULT now(), "updatedAt" TIMESTAMP NOT NULL DEFAULT now(), CONSTRAINT "UQ_b97a5a68c766d2d1ec25e6a85b2" UNIQUE ("phone"), CONSTRAINT "PK_92ab3fb69e566d3eb0cae896047" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE TABLE "time_windows" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "orderId" uuid NOT NULL, "driverId" uuid NOT NULL, "lowerBound" TIMESTAMP NOT NULL, "upperBound" TIMESTAMP NOT NULL, "windowWidthSeconds" integer NOT NULL, "expectedArrival" TIMESTAMP NOT NULL, "confidenceLevel" double precision NOT NULL, "violationProbability" double precision NOT NULL, "penaltyWidth" double precision NOT NULL, "penaltyEarly" double precision NOT NULL, "penaltyLate" double precision NOT NULL, "calculationMethod" character varying(50) NOT NULL, "sampleCount" integer, "travelTimeStdDev" double precision, "coefficientOfVariation" double precision, "actualArrival" TIMESTAMP, "wasWithinWindow" boolean, "deviationSeconds" integer, "createdAt" TIMESTAMP NOT NULL DEFAULT now(), "updatedAt" TIMESTAMP NOT NULL DEFAULT now(), CONSTRAINT "UQ_9c520f9d67b0d5fe2582df4bed1" UNIQUE ("orderId"), CONSTRAINT "PK_afd49e0b76e7f51b7ba8530741e" PRIMARY KEY ("id")); COMMENT ON COLUMN "time_windows"."lowerBound" IS 'Lower bound ℓ: earliest service time'; COMMENT ON COLUMN "time_windows"."upperBound" IS 'Upper bound u: latest service time'; COMMENT ON COLUMN "time_windows"."windowWidthSeconds" IS 'Window width in seconds: u - ℓ'; COMMENT ON COLUMN "time_windows"."expectedArrival" IS 'Expected arrival time E[T^k]'; COMMENT ON COLUMN "time_windows"."confidenceLevel" IS 'Service level guarantee (0-1): P(arrival ∈ [ℓ,u]). e.g., 0.95 = 95% on-time probability'; COMMENT ON COLUMN "time_windows"."violationProbability" IS 'Violation probability: 1 - confidenceLevel'; COMMENT ON COLUMN "time_windows"."penaltyWidth" IS 'Penalty a_w: cost per second of window width'; COMMENT ON COLUMN "time_windows"."penaltyEarly" IS 'Penalty a_ℓ: cost of early arrival'; COMMENT ON COLUMN "time_windows"."penaltyLate" IS 'Penalty a_u: cost of late arrival'; COMMENT ON COLUMN "time_windows"."calculationMethod" IS 'Method: stochastic_saa | distributionally_robust | simple_heuristic'; COMMENT ON COLUMN "time_windows"."sampleCount" IS 'Number of historical observations used (SAA)'; COMMENT ON COLUMN "time_windows"."travelTimeStdDev" IS 'Travel time standard deviation (seconds)'; COMMENT ON COLUMN "time_windows"."coefficientOfVariation" IS 'Coefficient of variation: σ/μ'; COMMENT ON COLUMN "time_windows"."wasWithinWindow" IS 'Whether actual ∈ [ℓ, u]'; COMMENT ON COLUMN "time_windows"."deviationSeconds" IS 'Deviation in seconds: negative=early, positive=late'`);
        await queryRunner.query(`CREATE TABLE "route_segment_observations" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "routeSegment" geometry(LineString,4326) NOT NULL, "estimatedSeconds" integer NOT NULL, "actualSeconds" integer NOT NULL, "deviationSeconds" integer NOT NULL, "distanceMeters" double precision NOT NULL, "driverId" uuid, "timeOfDay" character varying(20), "dayOfWeek" character varying(20), "weatherCondition" character varying(50), "timestamp" TIMESTAMP NOT NULL DEFAULT now(), CONSTRAINT "PK_953644963c282af0335e8efe4d3" PRIMARY KEY ("id")); COMMENT ON COLUMN "route_segment_observations"."routeSegment" IS 'Route segment as PostGIS LineString (start → end in SRID 4326)'; COMMENT ON COLUMN "route_segment_observations"."estimatedSeconds" IS 'Estimated travel time in seconds (from routing algorithm)'; COMMENT ON COLUMN "route_segment_observations"."actualSeconds" IS 'Actual observed travel time in seconds'; COMMENT ON COLUMN "route_segment_observations"."deviationSeconds" IS 'Deviation: actual - estimated (seconds, can be negative)'; COMMENT ON COLUMN "route_segment_observations"."distanceMeters" IS 'Distance calculated by PostGIS ST_Length using geography type (meters)'; COMMENT ON COLUMN "route_segment_observations"."timeOfDay" IS 'Time bucket: morning (6-12), afternoon (12-18), evening (18-22), night (22-6)'; COMMENT ON COLUMN "route_segment_observations"."dayOfWeek" IS 'Day: monday, tuesday, wednesday, thursday, friday, saturday, sunday'; COMMENT ON COLUMN "route_segment_observations"."weatherCondition" IS 'Weather condition during travel (if available)'`);
        await queryRunner.query(`CREATE INDEX "IDX_41db42720b56dc995cd3ec4e76" ON "route_segment_observations" USING GiST ("routeSegment") `);
        await queryRunner.query(`CREATE INDEX "IDX_f3205d0df4431d572cb49727c9" ON "route_segment_observations" ("timeOfDay", "dayOfWeek") `);
        await queryRunner.query(`CREATE INDEX "IDX_f7e295692ce643d0da805e05e8" ON "route_segment_observations" ("timestamp") `);
        await queryRunner.query(`CREATE INDEX "IDX_ce24c34d30d3389295db1c9fb1" ON "route_segment_observations" ("driverId") `);
        await queryRunner.query(`CREATE TABLE "draft_assignments" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "draft_group_id" integer NOT NULL, "driver_id" uuid NOT NULL, "order_id" uuid NOT NULL, "sequence" integer NOT NULL, "estimatedPickupTime" TIMESTAMP NOT NULL, "estimatedDeliveryTime" TIMESTAMP NOT NULL, "travelTimeToPickup" double precision NOT NULL, "travelTimeToDelivery" double precision NOT NULL, "metadata" jsonb, "createdAt" TIMESTAMP NOT NULL DEFAULT now(), CONSTRAINT "PK_02ed6da5bb4480fb8a462bacf50" PRIMARY KEY ("id")); COMMENT ON COLUMN "draft_assignments"."sequence" IS 'Position in driver route sequence (1-based)'; COMMENT ON COLUMN "draft_assignments"."estimatedPickupTime" IS 'Estimated pickup time'; COMMENT ON COLUMN "draft_assignments"."estimatedDeliveryTime" IS 'Estimated delivery time'; COMMENT ON COLUMN "draft_assignments"."travelTimeToPickup" IS 'Travel time from previous stop to pickup (minutes)'; COMMENT ON COLUMN "draft_assignments"."travelTimeToDelivery" IS 'Travel time from pickup to delivery (minutes)'; COMMENT ON COLUMN "draft_assignments"."metadata" IS 'Additional metadata about this assignment'`);
        await queryRunner.query(`CREATE TABLE "draft_groups" ("id" SERIAL NOT NULL, "sessionId" uuid NOT NULL, "totalTravelTime" double precision NOT NULL, "totalDistance" double precision NOT NULL, "averagePickupTime" double precision NOT NULL, "ordersCount" integer NOT NULL, "driversCount" integer NOT NULL, "metadata" jsonb NOT NULL, "isSelected" boolean NOT NULL DEFAULT false, "createdAt" TIMESTAMP NOT NULL DEFAULT now(), CONSTRAINT "PK_dfe5f6d94a6b3ae7bbb1defaa3b" PRIMARY KEY ("id")); COMMENT ON COLUMN "draft_groups"."sessionId" IS 'Links groups from same optimization run'; COMMENT ON COLUMN "draft_groups"."totalTravelTime" IS 'Sum of all travel times in minutes'; COMMENT ON COLUMN "draft_groups"."totalDistance" IS 'Sum of all distances in meters'; COMMENT ON COLUMN "draft_groups"."averagePickupTime" IS 'Average time to pickup across all orders'; COMMENT ON COLUMN "draft_groups"."ordersCount" IS 'Number of orders in this draft group'; COMMENT ON COLUMN "draft_groups"."driversCount" IS 'Number of drivers in this draft group'; COMMENT ON COLUMN "draft_groups"."metadata" IS 'Algorithm metadata and performance metrics'; COMMENT ON COLUMN "draft_groups"."isSelected" IS 'True if this is the selected/winning draft group'`);
        await queryRunner.query(`CREATE TABLE "distance_cache" ("id" character varying(100) NOT NULL, "origin" geometry(Point,4326) NOT NULL, "destination" geometry(Point,4326) NOT NULL, "profile" character varying(50) NOT NULL, "distance" double precision NOT NULL, "duration" double precision NOT NULL, "routeGeometry" jsonb, "createdAt" TIMESTAMP NOT NULL DEFAULT now(), "expiresAt" TIMESTAMP NOT NULL, CONSTRAINT "PK_3da9bd05d9020262d2c74116614" PRIMARY KEY ("id")); COMMENT ON COLUMN "distance_cache"."id" IS 'Hash of origin + destination + profile'; COMMENT ON COLUMN "distance_cache"."origin" IS 'Origin location as PostGIS Point'; COMMENT ON COLUMN "distance_cache"."destination" IS 'Destination location as PostGIS Point'; COMMENT ON COLUMN "distance_cache"."profile" IS 'Mapbox routing profile (e.g., driving-traffic, cycling)'; COMMENT ON COLUMN "distance_cache"."distance" IS 'Distance in meters'; COMMENT ON COLUMN "distance_cache"."duration" IS 'Duration in seconds'; COMMENT ON COLUMN "distance_cache"."routeGeometry" IS 'Optional GeoJSON route geometry'; COMMENT ON COLUMN "distance_cache"."expiresAt" IS 'Cache expiration time (TTL)'`);
        await queryRunner.query(`ALTER TABLE "driver_locations" ADD CONSTRAINT "FK_096de534e1c6301cf7f2a4bf032" FOREIGN KEY ("driver_id") REFERENCES "drivers"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "orders" ADD CONSTRAINT "FK_e5de51ca888d8b1f5ac25799dd1" FOREIGN KEY ("customerId") REFERENCES "customers"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "order_assignments" ADD CONSTRAINT "FK_2879b5a864ad805fe7332f68346" FOREIGN KEY ("order_id") REFERENCES "orders"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "order_assignments" ADD CONSTRAINT "FK_b94117859b7f0046739c2de5eae" FOREIGN KEY ("driver_id") REFERENCES "drivers"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "draft_assignments" ADD CONSTRAINT "FK_03121f11c3376046ece448ddfe9" FOREIGN KEY ("draft_group_id") REFERENCES "draft_groups"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "draft_assignments" ADD CONSTRAINT "FK_db7d578922c3b923ff0feda4278" FOREIGN KEY ("driver_id") REFERENCES "drivers"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "draft_assignments" ADD CONSTRAINT "FK_59cdef45d4b64f3230e9eae6e8f" FOREIGN KEY ("order_id") REFERENCES "orders"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
    }

    public async down(queryRunner: QueryRunner): Promise<void> {
        await queryRunner.query(`ALTER TABLE "draft_assignments" DROP CONSTRAINT "FK_59cdef45d4b64f3230e9eae6e8f"`);
        await queryRunner.query(`ALTER TABLE "draft_assignments" DROP CONSTRAINT "FK_db7d578922c3b923ff0feda4278"`);
        await queryRunner.query(`ALTER TABLE "draft_assignments" DROP CONSTRAINT "FK_03121f11c3376046ece448ddfe9"`);
        await queryRunner.query(`ALTER TABLE "order_assignments" DROP CONSTRAINT "FK_b94117859b7f0046739c2de5eae"`);
        await queryRunner.query(`ALTER TABLE "order_assignments" DROP CONSTRAINT "FK_2879b5a864ad805fe7332f68346"`);
        await queryRunner.query(`ALTER TABLE "orders" DROP CONSTRAINT "FK_e5de51ca888d8b1f5ac25799dd1"`);
        await queryRunner.query(`ALTER TABLE "driver_locations" DROP CONSTRAINT "FK_096de534e1c6301cf7f2a4bf032"`);
        await queryRunner.query(`DROP TABLE "distance_cache"`);
        await queryRunner.query(`DROP TABLE "draft_groups"`);
        await queryRunner.query(`DROP TABLE "draft_assignments"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_ce24c34d30d3389295db1c9fb1"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_f7e295692ce643d0da805e05e8"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_f3205d0df4431d572cb49727c9"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_41db42720b56dc995cd3ec4e76"`);
        await queryRunner.query(`DROP TABLE "route_segment_observations"`);
        await queryRunner.query(`DROP TABLE "time_windows"`);
        await queryRunner.query(`DROP TABLE "drivers"`);
        await queryRunner.query(`DROP TABLE "order_assignments"`);
        await queryRunner.query(`DROP TABLE "orders"`);
        await queryRunner.query(`DROP TABLE "customers"`);
        await queryRunner.query(`DROP TABLE "driver_locations"`);
    }

}
